### PR TITLE
Regular expression

### PR DESCRIPTION
**Pull request by tenaka**
Generalized the regular expression for matching the E-notation. For example it is possible to have a vertex

v 2.34143E-1 0.0 2.3

The same for normal and texture coordinates. 

It works for my use case but have not been extensively tested!

### CODE REVIEW

**Comment by cprogrammer1994** [comment]
Thank you!
I wrote some notes. Can you please check them?
I am willing to merge this and make a new release.

**Comment by tenaka** [comment]
Of course. Where do I find these notes?

**Comment by cprogrammer1994** [comment]
you should be able to see them above. or [here](https://github.com/cprogrammer1994/ModernGL.ext.obj/pull/3/files)

**Comment by tenaka** [comment]
I'm sorry. I see no notes above or in files changed that you linked to. Maybe I'm being stupid (it's my first pull request)..

**Comment by cprogrammer1994** [comment]
image

It is possible these notes are only visible for me. I am not sure.

**Comment by tenaka** [comment]
I did not see the notes. Good catch on the space. And it looks nicer to call .groups() instead of .groups(1,2,3).

I pushed the changes.

**Comment by cprogrammer1994** [comment]
Thank you!

**Pull request merged**
